# Generated by Django 6.0 on 2025-12-10 14:17

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0002_product_is_active_product_slug_productline'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProductImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('alternative_text', models.CharField(max_length=100)),
                ('url', models.ImageField(default='test.jpg', upload_to=None)),
                ('order', models.PositiveIntegerField()),
                ('productline', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='product_line', to='product.productline')),
            ],
        ),
    ]
